name: CI
on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
    cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: clemenscodes
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build --extra-experimental-features "nix-command flakes"
    - run: nix develop --extra-experimental-features "nix-command flakes"
